// RULE ZERO: every note, summary and label in this file is an abstract token or fixed
// product copy. Nothing here names an industry, sector, country, company or job title.

import { describe, it, expect } from 'vitest'
import { describeVersion, describeVersionHistory, type VersionRow } from '../version-history'

function row(over: Partial<VersionRow> = {}): VersionRow {
  return {
    id: 'id-1',
    version: '3',
    status: 'archived',
    created_at: '2026-09-01T10:00:00.000Z',
    update_trigger: 'signal_suggestion',
    revision_note: null,
    change_summary: null,
    ...over,
  }
}

describe('every version says something that distinguishes it', () => {
  it('prefers the note somebody typed', () => {
    const d = describeVersion(row({ revision_note: 'A note.', change_summary: 'A summary.' }))
    expect(d.description).toBe('A note.')
    expect(d.hasRecordedReason).toBe(true)
  })

  it('falls back to the change summary when there is no note', () => {
    const d = describeVersion(row({ change_summary: 'A summary.' }))
    expect(d.description).toBe('A summary.')
    expect(d.hasRecordedReason).toBe(true)
  })

  it('falls back to what produced it when there is neither', () => {
    const d = describeVersion(row())
    expect(d.description).toBe('Generated by your outbound team.')
    expect(d.hasRecordedReason).toBe(false)
  })

  it('never leaves a row blank, even with an unknown trigger', () => {
    // The four documents an organisation starts with have no note and no summary. A
    // blank row in the list is the failure this whole module exists to prevent.
    for (const trigger of [null, '', 'something_new_in_future']) {
      const d = describeVersion(row({ update_trigger: trigger }))
      expect(d.description.trim().length).toBeGreaterThan(0)
      expect(d.hasRecordedReason).toBe(false)
    }
  })

  it('treats whitespace as absent rather than as a note', () => {
    const d = describeVersion(row({ revision_note: '   \n ', change_summary: 'A summary.' }))
    expect(d.description).toBe('A summary.')
  })

  it('names a reverted version as one', () => {
    const d = describeVersion(row({ update_trigger: 'revert' }))
    expect(d.description).toBe('An earlier version put back.')
  })
})

describe('the live version is identified, and only one of them is', () => {
  it('marks status active as live', () => {
    expect(describeVersion(row({ status: 'active' })).isLive).toBe(true)
  })

  it.each(['archived', 'approved', 'draft', null])('does not mark %s as live', (status) => {
    expect(describeVersion(row({ status })).isLive).toBe(false)
  })
})

describe('the history is ordered newest first, whatever order it arrived in', () => {
  it('sorts by created_at descending', () => {
    const rows = [
      row({ id: 'a', version: '1', created_at: '2026-09-01T10:00:00.000Z' }),
      row({ id: 'c', version: '3', created_at: '2026-09-03T10:00:00.000Z', status: 'active' }),
      row({ id: 'b', version: '2', created_at: '2026-09-02T10:00:00.000Z' }),
    ]
    expect(describeVersionHistory(rows).map(d => d.id)).toEqual(['c', 'b', 'a'])
  })

  it('does not mutate the array it was given', () => {
    const rows = [
      row({ id: 'a', created_at: '2026-09-01T10:00:00.000Z' }),
      row({ id: 'b', created_at: '2026-09-03T10:00:00.000Z' }),
    ]
    describeVersionHistory(rows)
    expect(rows.map(r => r.id)).toEqual(['a', 'b'])
  })

  it('keeps every version, so five regenerations give five options', () => {
    const rows = Array.from({ length: 5 }, (_, i) =>
      row({
        id: `id-${i}`,
        version: String(i + 1),
        created_at: `2026-09-0${i + 1}T10:00:00.000Z`,
        revision_note: `Note ${i + 1}.`,
      }),
    )
    const described = describeVersionHistory(rows)
    expect(described).toHaveLength(5)
    expect(new Set(described.map(d => d.description)).size).toBe(5)
  })
})
