// What one row of a document's version history says on screen.
//
// DETERMINISTIC. A pure function over rows already fetched, per ADR-018.
//
// ─────────────────────────────────────────────────────────────────────────────
// THE ONE THING THIS EXISTS TO PREVENT
//
// A list of versions that cannot be told apart. Five regenerations produce five rows
// with the same document type, the same client and near-identical timestamps, and
// picking one to restore is a guess unless each row says what produced it.
//
// So every row gets a line, and the fallbacks are ordered by how much they actually
// tell the reader:
//
//   1. The note somebody typed. Always the best answer, because a human wrote it about
//      this specific version.
//   2. The change summary the agent wrote, when there is no note. Second best: it
//      describes the version rather than the reason for it.
//   3. A sentence derived from update_trigger. Weakest, and it says so, because
//      "Generated by your outbound team" distinguishes a version from a client revision
//      but not from another generation.
//
// Case 3 is not decoration. The four documents an organisation starts with have no note
// and no summary, and without it they would be blank rows in the list.
//
// RULE ZERO: nothing here names an industry, sector, country, company or job title.

export interface VersionRow {
  id: string
  version: string
  status: string | null
  created_at: string
  update_trigger: string | null
  revision_note: string | null
  change_summary: string | null
}

export interface DescribedVersion {
  id: string
  /** "Version 4" */
  label: string
  /** The line under the label. Never empty. */
  description: string
  /** True when this row is the document currently in force. */
  isLive: boolean
  /** True when the description came from a note or summary somebody actually wrote. */
  hasRecordedReason: boolean
  createdAt: string
}

const TRIGGER_DESCRIPTIONS: Record<string, string> = {
  signal_suggestion: 'Generated by your outbound team.',
  client_revision: 'Created from a change you asked for.',
  revert: 'An earlier version put back.',
  intake: 'Created from your intake answers.',
}

export function describeVersion(row: VersionRow): DescribedVersion {
  const note = row.revision_note?.trim()
  const summary = row.change_summary?.trim()

  let description: string
  let hasRecordedReason: boolean

  if (note) {
    description = note
    hasRecordedReason = true
  } else if (summary) {
    description = summary
    hasRecordedReason = true
  } else {
    // `??` alone is not enough here and the first version of this got it wrong: an
    // update_trigger of '' is neither null nor undefined, so `row.update_trigger && ...`
    // evaluated to '' and `??` passed it straight through as the description. The row
    // rendered blank, which is precisely the failure this module exists to prevent.
    // Resolved through a variable and checked for emptiness instead.
    const fromTrigger = row.update_trigger ? TRIGGER_DESCRIPTIONS[row.update_trigger] : undefined
    description = fromTrigger?.trim()
      ? fromTrigger
      : 'No note was recorded for this version.'
    hasRecordedReason = false
  }

  return {
    id: row.id,
    label: `Version ${row.version}`,
    description,
    isLive: row.status === 'active',
    hasRecordedReason,
    createdAt: row.created_at,
  }
}

/**
 * The whole history, newest first.
 *
 * Sorted HERE rather than trusted from the query, because the list is the thing a person
 * picks a version to restore from and "the one above" has to mean "the one after".
 */
export function describeVersionHistory(rows: VersionRow[]): DescribedVersion[] {
  return [...rows]
    .sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime())
    .map(describeVersion)
}
