// Shared TypeScript types for MargenticOS.
// Database types will be generated by Supabase CLI and live in types/database.ts.
// Add application-layer types here as they are built.

export type UserRole = 'operator' | 'client'

export type DocumentType = 'icp' | 'positioning' | 'tov' | 'messaging'

export type SignalType =
  | 'email_open'
  | 'email_click'
  | 'email_reply'
  | 'email_bounce'
  | 'email_spam'
  | 'linkedin_post_like'
  | 'linkedin_post_comment'
  | 'linkedin_post_share'
  | 'linkedin_dm_reply'
  | 'linkedin_connection_accepted'
  | 'meeting_qualified'
  | 'meeting_unqualified'
  | 'meeting_no_show'
  | 'positive_reply'
  | 'information_request'
  | 'opt_out'
  | 'out_of_office'

export type CampaignType = 'cold_email' | 'linkedin_post' | 'linkedin_dm'

export type MeetingQualification = 'qualified' | 'unqualified' | 'pending'

export type WarningLevel = 'green' | 'amber' | 'red'

export type ConnectionStatus = 'connected' | 'disconnected' | 'error'

export type SuggestionStatus = 'pending' | 'approved' | 'rejected' | 'superseded'

export type ConfidenceLevel = 'low' | 'medium' | 'high'

// ─── ICP Document types ───────────────────────────────────────────────────────
// These describe the JSON structure stored in strategy_documents.content
// and in document_suggestions.suggested_value for ICP documents.

export interface IcpBuyerProfile {
  title: string
  seniority: string
  day_to_day: string
  identity: string
}

export interface IcpCompanyProfile {
  revenue_range: string
  headcount: string
  stage: string
  industries: string[]
  geography: string
  business_model: string
}

export interface IcpFourForces {
  push: string[]
  pull: string[]
  anxiety: string[]
  habit: string[]
}

export interface IcpTier {
  label: string
  description: string
  company_profile: IcpCompanyProfile
  buyer_profile: IcpBuyerProfile
  four_forces: IcpFourForces
  triggers: string[]
  switching_costs: string[]
  disqualifiers: string[]
}

export interface IcpDocument {
  jtbd_statement: string
  summary: string
  tier_1: IcpTier
  tier_2: IcpTier
  tier_3: IcpTier
}
