// A repair may only fill a slot alongside copy written from the SAME strategy documents.
//
// THE INCIDENT THIS IS WRITTEN AGAINST, measured in production 2026-09-21: variants A, C
// and D were written against ICP v5; another session approved ICP v6 eleven minutes before
// a repair ran; the repair read the ACTIVE ICP, got v6, and wrote a fourth variant derived
// from a different buyer profile into the same document. The byte-level payload guard
// passed, correctly, because it was checking something else entirely.
//
// Both directions matter here. A guard that refuses everything stops repairs working at
// all, and a guard that passes on an unreadable provenance is the original bug wearing a
// check's name.
//
// Industry-neutral throughout (Rule Zero).

import { describe, it, expect } from 'vitest'
import {
  assertSourceVersionsUnchanged,
  changedDocuments,
  formatSourceVersions,
  parseSourceVersions,
  SourceProvenanceError,
  type SourceVersions,
} from '../source-provenance'

// The exact tail the generation agent writes, reproduced so the parser is tested against
// the real shape rather than against one invented for the test.
const REAL_REASON =
  'Four-variant Messaging Playbook generated by messaging-generation-agent using ' +
  'claude-sonnet-4-6. Refresh. Version 5 supplied to the agent as context. Intake ' +
  'completeness: 100% (15/15 required fields). Variants passed: A, C, D. Variants dropped ' +
  'after retries: B. Passed on retry: A (attempt 1), C (attempt 1), D (attempt 1). Dropped ' +
  'after all retries: B. Total API calls: 6. Duration: 195s. ' +
  'Source documents: ICP v5, Positioning v2, TOV v3.'

const V5: SourceVersions = { icp: '5', positioning: '2', tov: '3' }
const V6: SourceVersions = { icp: '6', positioning: '2', tov: '3' }

describe('parseSourceVersions', () => {
  it('reads the versions out of a real suggestion_reason', () => {
    expect(parseSourceVersions(REAL_REASON)).toEqual(V5)
  })

  it('reads them when the run appended more text afterwards', () => {
    const withRepairNote = REAL_REASON +
      ' Variant B was repaired separately on 2026-09-21 by messaging-variant-repair.'
    expect(parseSourceVersions(withRepairNote)).toEqual(V5)
  })

  it('returns null for a reason that never recorded them', () => {
    expect(parseSourceVersions('Generated by an older agent that recorded nothing.')).toBeNull()
  })

  it('returns null for an empty reason', () => {
    expect(parseSourceVersions(null)).toBeNull()
    expect(parseSourceVersions('')).toBeNull()
  })

  // Anchored on the literal label, so prose that merely mentions a version is not mistaken
  // for the provenance record.
  it('does not mistake a version mentioned in passing for the record', () => {
    expect(parseSourceVersions('Version 5 supplied to the agent as context.')).toBeNull()
  })

  it('round-trips through formatSourceVersions', () => {
    const formatted = `Source documents: ${formatSourceVersions(V5)}.`
    expect(parseSourceVersions(formatted)).toEqual(V5)
  })
})

describe('changedDocuments', () => {
  it('reports nothing when all three match', () => {
    expect(changedDocuments(V5, { ...V5 })).toEqual([])
  })

  it('names the ICP when only the ICP moved', () => {
    expect(changedDocuments(V5, V6)).toEqual(['ICP'])
  })

  it('names every document that moved, in a stable order', () => {
    expect(changedDocuments(V5, { icp: '6', positioning: '3', tov: '4' }))
      .toEqual(['ICP', 'Positioning', 'TOV'])
  })

  it('notices Positioning and TOV, not just the ICP', () => {
    expect(changedDocuments(V5, { icp: '5', positioning: '3', tov: '3' })).toEqual(['Positioning'])
    expect(changedDocuments(V5, { icp: '5', positioning: '2', tov: '4' })).toEqual(['TOV'])
  })
})

describe('assertSourceVersionsUnchanged', () => {
  // THE PROCEED DIRECTION. A guard that never lets a repair through is an outage.
  it('PROCEEDS and returns the versions when nothing changed', () => {
    const result = assertSourceVersionsUnchanged({
      suggestionReason: REAL_REASON,
      current: { ...V5 },
      variantKey: 'B',
    })
    expect(result).toEqual(V5)
  })

  // THE REFUSAL DIRECTION, and the exact case that reached production.
  it('REFUSES when the ICP has been approved anew since the survivors were written', () => {
    expect(() => assertSourceVersionsUnchanged({
      suggestionReason: REAL_REASON,
      current: V6,
      variantKey: 'B',
    })).toThrow(SourceProvenanceError)
  })

  it('names the document, both versions and the variant in the refusal', () => {
    let message = ''
    try {
      assertSourceVersionsUnchanged({ suggestionReason: REAL_REASON, current: V6, variantKey: 'B' })
    } catch (err) {
      message = (err as Error).message
    }
    expect(message).toContain('a source document has changed')
    expect(message).toContain('ICP')
    expect(message).toContain('recorded v5, now v6')
    expect(message).toContain('CHANGED')
    expect(message).toContain('Filling variant B')
    expect(message).toContain('Regenerate the whole document')
    // The documents that did NOT move are shown too, so the reader can see the full
    // comparison rather than only the failing line.
    expect(message).toContain('Positioning  recorded v2, now v2')
  })

  it('pluralises correctly when more than one document moved', () => {
    let message = ''
    try {
      assertSourceVersionsUnchanged({
        suggestionReason: REAL_REASON,
        current: { icp: '6', positioning: '3', tov: '3' },
        variantKey: 'B',
      })
    } catch (err) {
      message = (err as Error).message
    }
    expect(message).toContain('source documents have changed')
    expect(message).toContain('ICP and Positioning')
  })

  // AN UNREADABLE PROVENANCE IS A REFUSAL. This is the one that would otherwise look
  // harmless: "no record" is not "no change".
  it('REFUSES when the suggestion records no provenance at all', () => {
    expect(() => assertSourceVersionsUnchanged({
      suggestionReason: 'Generated by an older agent that recorded nothing.',
      current: V5,
      variantKey: 'B',
    })).toThrow(/does not record which strategy documents/)
  })

  it('REFUSES on a null reason rather than treating it as unchanged', () => {
    expect(() => assertSourceVersionsUnchanged({
      suggestionReason: null,
      current: V5,
      variantKey: 'B',
    })).toThrow(SourceProvenanceError)
  })

  it('REFUSES when Positioning moved even though the ICP did not', () => {
    expect(() => assertSourceVersionsUnchanged({
      suggestionReason: REAL_REASON,
      current: { icp: '5', positioning: '3', tov: '3' },
      variantKey: 'C',
    })).toThrow(/Positioning/)
  })
})
