-- Carry the note that produced a version onto the version.
--
-- Status: APPLIED (verified live 2026-09-03)
--
-- ─── THE DEFECT ───────────────────────────────────────────────────────────────
--
-- Found on 2026-09-03 while setting up the proof run for version history, not by reading
-- code, and it would have made the whole feature useless in its main case.
--
-- An operator regenerates a document with a note, approves the suggestion, and the
-- version that results has revision_note NULL. approve_document_suggestion passed NULL
-- for p_revision_note, and nothing had ever written the note onto the suggestion row
-- either. So five regenerations produced five versions that all rendered as "Generated by
-- your outbound team", with the same document type and near-identical timestamps.
--
-- Picking one to restore would have been a guess. "Without the note they are
-- indistinguishable" was the requirement, and this was the path that broke it.
--
-- Two halves, both needed, both in this commit:
--   1. The agents write noteForVersionHistory(regeneration_notes) to
--      document_suggestions.revision_note when they create the suggestion.
--   2. This migration makes approve_document_suggestion pass that value through to
--      promote_strategy_doc_version instead of NULL.
--
-- It also fixes a quieter case that was already losing information: a CLIENT revision to
-- messaging is staged as a suggestion carrying the client's own note in the same column,
-- and approving it discarded that note too. Now it survives onto the version.
--
-- ─── DOWN ─────────────────────────────────────────────────────────────────────
-- Restore the definition in 20260603_strategy_docs_revision.sql.

BEGIN;

CREATE OR REPLACE FUNCTION public.approve_document_suggestion(p_suggestion_id uuid, p_reviewer_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
 SET row_security TO 'off'
AS $function$
DECLARE
  v_suggestion record;
  v_content    jsonb;
  v_new_doc    jsonb;
BEGIN
  SELECT * INTO v_suggestion
  FROM document_suggestions
  WHERE id = p_suggestion_id AND status = 'pending'
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Suggestion % not found or not in pending status', p_suggestion_id;
  END IF;

  BEGIN
    v_content := v_suggestion.suggested_value::jsonb;
  EXCEPTION WHEN others THEN
    RAISE EXCEPTION 'suggested_value is not valid JSON for suggestion %', p_suggestion_id;
  END;

  IF v_suggestion.document_type = 'messaging' THEN
    IF v_content -> 'variants' IS NULL THEN
      RAISE EXCEPTION 'Messaging suggestion % is missing the variants key in suggested_value', p_suggestion_id;
    END IF;
  END IF;

  -- Delegate archival + versioning + insert to the shared helper.
  --
  -- p_revision_note was NULL here until 2026-09-03, which is what made every version
  -- created through this path indistinguishable in the history.
  SELECT promote_strategy_doc_version(
    v_suggestion.organisation_id,
    v_suggestion.document_type,
    v_suggestion.segment_id,
    v_content,
    'signal_suggestion',
    v_suggestion.revision_note,
    NULL
  ) INTO v_new_doc;

  UPDATE document_suggestions
  SET
    status      = 'approved',
    reviewed_at = now(),
    reviewed_by = p_reviewer_id
  WHERE id = p_suggestion_id;

  RETURN v_new_doc;
END;
$function$;

REVOKE ALL ON FUNCTION public.approve_document_suggestion(uuid, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.approve_document_suggestion(uuid, uuid) FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.approve_document_suggestion(uuid, uuid) TO service_role;

COMMIT;
